### ISSUE TITLE
Uninitialized Constant Formulaic (NameError)

### ISSUE THREAD

**Issue by draconiandev** [thoughtbot/formulaic#58]
Hi, I am trying to integrate Formulaic into my RSpec test suite. But whenever I include the config.include Formulaic::Dsl, type: :feature line in the spec_helper.rb, I am getting the following error.

I am running on Rails 4.2.5.2 and the Formulaic version in 0.3.0. I tried the same with another app running on 4.2.5. It's been the same. It would be really great if someone can point what I am doing wrong. 

Thank You.

Here is the trace.

```
/home/p150/Documents/code/booker/spec/spec_helper.rb:18:in `<top (required)>': uninitialized constant Formulaic (NameError)
	from /home/p150/.rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/p150/.rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/p150/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.3/lib/rspec/core/configuration.rb:1295:in `block in requires='
	from /home/p150/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.3/lib/rspec/core/configuration.rb:1295:in `each'
	from /home/p150/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.3/lib/rspec/core/configuration.rb:1295:in `requires='
	from /home/p150/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.3/lib/rspec/core/configuration_options.rb:109:in `block in process_options_into'
	from /home/p150/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.3/lib/rspec/core/configuration_options.rb:108:in `each'
	from /home/p150/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.3/lib/rspec/core/configuration_options.rb:108:in `process_options_into'
	from /home/p150/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.3/lib/rspec/core/configuration_options.rb:21:in `configure'
	from /home/p150/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.3/lib/rspec/core/runner.rb:105:in `setup'
	from /home/p150/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.3/lib/rspec/core/runner.rb:92:in `run'
	from /home/p150/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.3/lib/rspec/core/runner.rb:78:in `run'
	from /home/p150/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.3/lib/rspec/core/runner.rb:45:in `invoke'
	from /home/p150/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.3/exe/rspec:4:in `<top (required)>'
	from /home/p150/.rbenv/versions/2.3.0/bin/rspec:22:in `load'
	from /home/p150/.rbenv/versions/2.3.0/bin/rspec:22:in `<main>'
```

**Comment by calebthompson** [comment]
Did you `require 'formulaic'`?

**Comment by draconiandev** [comment]
Yes, I tried that as well.

**Comment by calebthompson** [comment]
Can you share your spec_helper
